widgets: 
    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: 大只若于
        # Author title
        author_title: 宇宙社会学研究员
        # Author's current location
        location: 半人马座α星
        # URL or path to the avatar image
        avatar: /img/Sanatan.jpg
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: https://github.com/imyukehan
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/imyukehan
            Facebook:
                icon: fab fa-facebook
                url: https://www.facebook.com/profile.php?id=100021633186218
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com/imyukehan
            RSS:
                icon: fas fa-rss
                url: /
    # 目录Widget开启，需要文章开头添加'toc: true'
    -
        type: toc
        position: left
        # 是否显示目录项目的序号
        index: true
    # Recent posts widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: recent_posts